name: build
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: node
        run: echo "::set-output name=version::$(cat .nvmrc)"
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.node.version }}"
          cache: yarn
      - run: yarn
      - run: yarn build
