name: e2e
on:
  - push
  - workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: node
        run: echo "::set-output name=version::$(cat .nvmrc)"
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.node.version }}"
          cache: yarn
      - run: yarn
        env: { PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true" }
      - name: Install Japanese fonts.
        run: sudo apt-get install fonts-noto-cjk
      - id: test
        run: xvfb-run yarn e2e
      - if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: test/e2e/screenshots
      - if: success() || failure()
        name: Upload to Slack
        run: test/e2e/bin/upload-screenshots
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNELS: ${{ secrets.SLACK_CHANNELS }}
      - if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: videomark-mini-stats-screenshots
          path: packages/videomark-mini-stats/screenshots
